server {
    listen 80;
    server_name devops-minahil.myftp.biz;

    # Redirect all HTTP traffic to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name devops-minahil.myftp.biz;

    ssl_certificate     /etc/letsencrypt/live/devops-minahil.myftp.biz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/devops-minahil.myftp.biz/privkey.pem;

    location /api/ {
        proxy_pass http://api:5000;
    }

    location / {
        proxy_pass http://web:3000;
    }
}
